config/routes.rb
Rails.application.routes.draw do
  get 'flights/index'
  get 'flights/show'
  get 'flights/new'
  get 'flights/create'
  get 'flights/edit'
  get 'flights/update'
  get 'flights/destroy'
  get 'bookings/index', to: 'bookings#index', as: 'bookings_index'
  get 'bookings/show'
  get '/:flight_number/bookings/new', to: 'bookings#new', as: 'bookings_new'
  post '/:flight_number/bookings/create', to: 'bookings#create', as: 'bookings_create'
  get 'bookings/edit'
  get 'bookings/update'
  delete 'bookings/destroy/:id', to: 'bookings#destroy', as:'bookings_destroy'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "flights#index"
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :flights

  enum class_type: { economy: 0, business: 1 }

  validates :passenger_number, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 99 }
  validates :code_pnr, presence: true, uniqueness: true

  def self.generate_pnr_code
    characters = ('A'..'Z').to_a + ('0'..'9').to_a
    characters.sample(6).join
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @current_bookings = current_user.bookings.joins(:flights).where('flights.departure_date >= ?', Time.zone.now).order('flights.departure_date DESC')
    @past_bookings = current_user.bookings.joins(:flights).where('flights.departure_date < ?', Time.zone.now).order('flights.departure_date DESC')
  end


  def show
  end

  def new
    flight_number = params[:flight_number]
    @flight = Flight.find_by(number: flight_number)
    if user_signed_in? && @flight.departure_date > DateTime.current.in_time_zone("UTC")
      @booking = Booking.new
    else
      redirect_to root_path
    end
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.code_pnr = Booking.generate_pnr_code
    @booking.user = current_user

    flight_number = params[:flight_number]
    @flight = Flight.find_by(number: flight_number)
    @booking.flights << @flight

    if user_signed_in? && booking_validation(@flight, @booking) && @booking.save
      ApplicationMailer.mailer(current_user.email, @flight, @booking).deliver_now
      redirect_to bookings_index_path, notice: t('booking.success')
    else
      flash[:error] = @booking.errors.full_messages.join(", ")
      redirect_to bookings_new_path, flight_number: flight_number
    end
  end

  def booking_validation(flight, booking)
    class_type = booking.class_type
    class_type_seat_count = flight.bookings.where(class_type: class_type).sum(:passenger_number)
    available_seats = booking.economy? ? flight.economy_class_seats : flight.business_class_seats

    if booking.passenger_number === nil
      booking.errors.add(:base, t('booking.errors.bad_passenger_number'))
      return false
    end

    if class_type_seat_count + booking.passenger_number > available_seats
      booking.errors.add(:base, t('booking.errors.not_enough_seats'))
      return false
    end

    true
  end

  def booking_params
    params.require(:booking).permit(:class_type, :passenger_number)
  end

  def edit
  end

  def update
  end
  def destroy
    booking = Booking.find(params[:id])
    booking.destroy

    redirect_to bookings_index_path, notice: 'Réservation supprimée avec succès.'
  end

end

app/views/bookings/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Bookings#create</h1>
  <p>Find me in app/views/bookings/create.html.erb</p>
</div>

app/views/bookings/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Bookings#destroy</h1>
  <p>Find me in app/views/bookings/destroy.html.erb</p>
</div>

app/views/bookings/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">Bookings#edit</h1>
  <p>Find me in app/views/bookings/edit.html.erb</p>
</div>

app/views/bookings/index.html.erb
<div class="flex flex-col items-center justify-center flex-grow bg-orange-100 py-8">
  <h1 class="text-slate-900 text-3xl font-bold"><%= t('booking.label') %></h1>
  <div class="flex flex-col w-[1000px] bg-white shadow-lg rounded-lg my-8 px-8 py-6 gap-6">
    <h2 class="text-slate-900 text-2xl font-bold"><%= t('flight.next_flights') %></h2>
    <% if @current_bookings.length === 0 %>
      <p class="text-gray-500 text-center"><%= t('flight.no_next_flights') %></p>
    <% else %>
      <%= render 'shared/booking_details', bookings: @current_bookings, can_cancel: true %>
    <% end %>
    <hr class="my-8"/>
    <h2 class="text-slate-900 text-2xl font-bold"><%= t('flight.past_flights') %></h2>
    <% if @past_bookings.length === 0 %>
      <p class="text-gray-500 text-center"><%= t('flight.no_past_flights') %></p>
    <% else %>
      <%= render 'shared/booking_details', bookings: @past_bookings, can_cancel: false %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="flex flex-grow bg-orange-100">
  <div class="flex flex-col justify-center items-center flex-grow">
    <div class="min-w-[60%]">
      <%= form_with(model: @booking, url: bookings_create_path(flight_number: @flight.number), html: { class: "flex flex-col gap-6 bg-white text-slate-900 p-6 rounded-lg overflow-hidden drop-shadow-lg" }) do |form| %>

        <h1 class="text-2xl text-center font-bold mb-4"><%= t('booking.book_flight_seats') %></h1>

        <div class="relative">
          <%= form.select :class_type, options_for_select(Booking.class_types.keys.map { |key| [t("booking.class_types.#{key}"), key] }), {}, { class: "block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer uppercase" } %>
          <%= form.label :class_type, t('booking.class_type_label'), class: "absolute text-sm text-gray-500 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1" %>
        </div>

        <div class="relative">
          <%= form.number_field :passenger_number, placeholder: " ", class: "block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer" %>
          <%= form.label :passenger_number, t('booking.passenger_number_label'), class: "absolute text-sm text-gray-500 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1" %>
        </div>

        <% if flash[:error] %>
          <div class="flex items-center gap-2 p-4 bg-red-100 text-red-700 rounded-lg border border-red-700">
            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M256 32c14.2 0 27.3 7.5 34.5 19.8l216 368c7.3 12.4 7.3 27.7 .2 40.1S486.3 480 472 480H40c-14.3 0-27.6-7.7-34.7-20.1s-7-27.8 .2-40.1l216-368C228.7 39.5 241.8 32 256 32zm0 128c-13.3 0-24 10.7-24 24V296c0 13.3 10.7 24 24 24s24-10.7 24-24V184c0-13.3-10.7-24-24-24zm32 224a32 32 0 1 0 -64 0 32 32 0 1 0 64 0z"/></svg>
            <%= flash[:error] %>
          </div>
        <% end %>

        <%= form.submit t('booking.booking_button'), class: "cursor-pointer text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center" %>
      <% end %>
    </div>
  </div>

  <div class="min-w-[40%] flex flex-col justify-center items-center">
    <div class="min-w-[60%]">
      <%= render "shared/flight_details", flight: @flight %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Bookings#show</h1>
  <p>Find me in app/views/bookings/show.html.erb</p>
</div>

app/views/bookings/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Bookings#update</h1>
  <p>Find me in app/views/bookings/update.html.erb</p>
</div>