config/routes.rb
Rails.application.routes.draw do
  get 'flights/index'
  get 'flights/show'
  get 'flights/new'
  get 'flights/create'
  get 'flights/edit'
  get 'flights/update'
  get 'flights/destroy'
  get 'bookings/index', to: 'bookings#index', as: 'bookings_index'
  get 'bookings/show'
  get '/:flight_number/bookings/new', to: 'bookings#new', as: 'bookings_new'
  post '/:flight_number/bookings/create', to: 'bookings#create', as: 'bookings_create'
  get 'bookings/edit'
  get 'bookings/update'
  delete 'bookings/destroy/:id', to: 'bookings#destroy', as:'bookings_destroy'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "flights#index"
end

app/views/shared/_booking_details.html.erb
<div class="flex flex-col gap-4">
  <% bookings.each do |booking| %>
    <% booking.flights.each_with_index do |flight| %>
      <div class="flex justify-between items-center bg-white text-slate-900 p-6 rounded-lg overflow-hidden drop-shadow-lg hover:drop-shadow-xl">
        <div>
          <div class="flex items-center gap-2 pl-2 pb-4">
            <span class="text-xs px-2 py-1 rounded-full bg-blue-100 text-blue-700">N°<%= flight.number %></span>
            <% if flight.departure_date.day === Flight.arrival_date(flight.departure_date, flight.duration).day %>
              <p><%= l flight.departure_date.to_date, :format => :full %></p>
            <% else %>
              <p><%= l flight.departure_date.to_date, :format => :full %> - <%= l Flight.arrival_date(flight.departure_date, flight.duration).to_date, :format => :full %></p>
            <% end %>
          </div>
          <ol class="relative">
            <li class="relative pl-24 pb-16">
              <span class="absolute left-2.5 font-bold"><%= flight.departure_date.strftime("%H:%M") %></span>
              <p class="text-blue-900"><span class="font-bold"><%= Flight.airport_name(flight.departure_airport) %></span> (<%= flight.departure_airport %>)</p>
            </li>
            <li class="Time absolute flex items-center gap-1 text-sm top-12 left-24">
              <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M464 256A208 208 0 1 1 48 256a208 208 0 1 1 416 0zM0 256a256 256 0 1 0 512 0A256 256 0 1 0 0 256zM232 120V256c0 8 4 15.5 10.7 20l96 64c11 7.4 25.9 4.4 33.3-6.7s4.4-25.9-6.7-33.3L280 243.2V120c0-13.3-10.7-24-24-24s-24 10.7-24 24z"/></svg>
              <%= Flight.duration_to_human_readable(flight.duration) %>
            </li>
            <li class="relative pl-24">
              <span class="absolute left-2.5 font-bold"><%= Flight.arrival_date(flight.departure_date, flight.duration).strftime("%H:%M") %></span>
              <p class="text-blue-900"><span class="font-bold"><%= Flight.airport_name(flight.arrival_airport) %></span> (<%= flight.arrival_airport %>)</p>
            </li>
          </ol>
        </div>

        <div class="flex flex-col gap-4">
          <div class="flex flex-col gap-2">
            <p class="text-xs px-4 py-2 rounded-full text-orange-700 bg-orange-100 font-bold uppercase">
              <%= t("booking.class_types.#{booking.class_type}") %>
            </p>
            <p class="text-xs px-4 py-2 rounded-full text-blue-700 bg-blue-100">
              <span class="font-bold"><%= booking.passenger_number %></span> <%= t('booking.seats_booked') %>
            </p>
          </div>
          <% if can_cancel %>
            <%= button_to t('booking.cancel'), bookings_destroy_path(id: booking.id), method: :delete, class: "w-full text-center text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-4 dark:bg-red-600 dark:hover:bg-red-700 focus:outline-none dark:focus:ring-red-800" %>
        <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_flight_details.html.erb
<div>
  <h2 class="text-lg font-medium text-gray-800 truncate text-center"><%= flight.number %></h2>

  <div class="flex justify-between ">
    <div class="text-center flex-col items-center flex ">
      <p class="text-sm font-medium text-gray-600 mt-2"><%= t('flight.departure_date') %></p>
      <p class="text-md text-gray-800 mb-4"><%= flight.departure_date %></p>
      <div class="h-16 w-16 bg-blue-500 relative rounded-full">
        <svg  class="translate-center  top-1/2 left-1/2 absolute" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><!--! Font Awesome Pro 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M381 114.9L186.1 41.8c-16.7-6.2-35.2-5.3-51.1 2.7L89.1 67.4C78 73 77.2 88.5 87.6 95.2l146.9 94.5L136 240 77.8 214.1c-8.7-3.9-18.8-3.7-27.3 .6L18.3 230.8c-9.3 4.7-11.8 16.8-5 24.7l73.1 85.3c6.1 7.1 15 11.2 24.3 11.2H248.4c5 0 9.9-1.2 14.3-3.4L535.6 212.2c46.5-23.3 82.5-63.3 100.8-112C645.9 75 627.2 48 600.2 48H542.8c-20.2 0-40.2 4.8-58.2 14L381 114.9zM0 480c0 17.7 14.3 32 32 32H608c17.7 0 32-14.3 32-32s-14.3-32-32-32H32c-17.7 0-32 14.3-32 32z"/></svg>
      </div>
      <p class="text-sm font-medium text-gray-600"><%= t('flight.departure_airport') %></p>
      <p class="text-md text-gray-800 mb-4"><%= Flight.airport_name(flight.departure_airport) %> (<%= flight.departure_airport %>)</p>
    </div>

    <div class="text-center flex-col items-center flex ">
      <p class="text-sm font-medium text-gray-600 mt-2"><%= t('flight.arrival_date') %></p>
      <p class="text-md text-gray-800 mb-4"><%= flight.departure_date+flight.duration.minutes %></p>
      <div class="h-16 w-16 bg-blue-500 relative rounded-full">
        <svg class="translate-center  top-1/2 left-1/2 absolute"  xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><!--! Font Awesome Pro 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M.3 166.9L0 68C0 57.7 9.5 50.1 19.5 52.3l35.6 7.9c10.6 2.3 19.2 9.9 23 20L96 128l127.3 37.6L181.8 20.4C178.9 10.2 186.6 0 197.2 0h40.1c11.6 0 22.2 6.2 27.9 16.3l109 193.8 107.2 31.7c15.9 4.7 30.8 12.5 43.7 22.8l34.4 27.6c24 19.2 18.1 57.3-10.7 68.2c-41.2 15.6-86.2 18.1-128.8 7L121.7 289.8c-11.1-2.9-21.2-8.7-29.3-16.9L9.5 189.4c-5.9-6-9.3-14-9.3-22.5zM32 448H608c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32zm96-80a32 32 0 1 1 64 0 32 32 0 1 1 -64 0zm128-16a32 32 0 1 1 0 64 32 32 0 1 1 0-64z"/></svg>
      </div>
      <p class="text-sm font-medium text-gray-600"><%= t('flight.arrival_airport') %></p>
      <p class="text-md text-gray-800 mb-4"><%= Flight.airport_name(flight.arrival_airport) %> (<%= flight.arrival_airport %>)</p>
    </div>
  </div>
</div>

app/views/shared/_flight_item.html.erb
<div class="flex justify-between items-center bg-white text-slate-900 p-6 rounded-lg overflow-hidden drop-shadow-lg hover:drop-shadow-xl">
  <div>
    <div class="flex items-center gap-2 pl-2 pb-4">
      <span class="text-xs px-2 py-1 rounded-full bg-blue-100 text-blue-700">N°<%= flight.number %></span>
      <% if flight.departure_date.day === Flight.arrival_date(flight.departure_date, flight.duration).day %>
        <p><%= l flight.departure_date.to_date, :format => :full %></p>
      <% else %>
        <p><%= l flight.departure_date.to_date, :format => :full %> - <%= l Flight.arrival_date(flight.departure_date, flight.duration).to_date, :format => :full %></p>
      <% end %>
    </div>
    <ol class="relative">
      <li class="relative pl-24 pb-16">
        <span class="absolute left-2.5 font-bold"><%= flight.departure_date.strftime("%H:%M") %></span>
        <p class="text-blue-900"><span class="font-bold"><%= Flight.airport_name(flight.departure_airport) %></span> (<%= flight.departure_airport %>)</p>
      </li>
      <li class="Time absolute flex items-center gap-1 text-sm top-12 left-24">
        <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M464 256A208 208 0 1 1 48 256a208 208 0 1 1 416 0zM0 256a256 256 0 1 0 512 0A256 256 0 1 0 0 256zM232 120V256c0 8 4 15.5 10.7 20l96 64c11 7.4 25.9 4.4 33.3-6.7s4.4-25.9-6.7-33.3L280 243.2V120c0-13.3-10.7-24-24-24s-24 10.7-24 24z"/></svg>
        <%= Flight.duration_to_human_readable(flight.duration) %>
      </li>
      <li class="relative pl-24">
        <span class="absolute left-2.5 font-bold"><%= Flight.arrival_date(flight.departure_date, flight.duration).strftime("%H:%M") %></span>
        <p class="text-blue-900"><span class="font-bold"><%= Flight.airport_name(flight.arrival_airport) %></span> (<%= flight.arrival_airport %>)</p>
      </li>
    </ol>
  </div>

  <div class="flex flex-col gap-4">
    <div class="flex flex-col gap-2">
      <p class="text-xs px-4 py-2 rounded-full text-green-700 bg-green-100">
        <span class="font-bold"><%= flight.economy_available_seats %></span> <%= t('flight.economy_available_seats') %>
      </p>
      <p class="text-xs px-4 py-2 rounded-full text-amber-700 bg-amber-100">
        <span class="font-bold"><%= flight.business_available_seats %></span> <%= t('flight.business_available_seats') %>
      </p>
    </div>
    <% if user_signed_in? %>
      <%= link_to t('booking.booking_button'), bookings_new_path(flight_number: flight.number), class: "text-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-4 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
    <% else %>
      <%= link_to t('booking.booking_button'), new_user_session_path, class: "text-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-4 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
    <% end %>
  </div>
</div>

app/views/shared/_menu.html.erb
<nav class="bg-blue-900 px-4 py-2 flex items-center justify-between shadow-xl sticky top-0 left-0 z-10">
  <div class="flex items-center">
    <%= link_to "/", class: "flex items-center" do %>
      <%= image_tag("/logo2.png", alt: "Logo", class: "h-16 mr-2") %>
      <span class="text-white font-semibold text-xl tracking-tight">Flyght Club</span>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <div class="flex items-center gap-4 text-white">
      <%= link_to t('booking.label'), bookings_index_path, class: "text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center" %>
      <div class="flex divide-x">
        <div class="flex items-center pr-2 gap-2">
          <p><%= current_user.email %></p>
          <svg class="w-8 h-8" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
            <path d="M399 384.2C376.9 345.8 335.4 320 288 320H224c-47.4 0-88.9 25.8-111 64.2c35.2 39.2 86.2 63.8 143 63.8s107.8-24.7 143-63.8zM0 256a256 256 0 1 1 512 0A256 256 0 1 1 0 256zm256 16a72 72 0 1 0 0-144 72 72 0 1 0 0 144z"/>
          </svg>
        </div>
        <div class="pl-2">
          <%= button_to t('auth.sign_out'), destroy_user_session_path, method: :delete, class: "text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center" %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="flex items-center gap-2 text-white">
      <%= link_to t('auth.sign_up'), new_user_registration_path, class: "block mt-4 lg:inline-block lg:mt-0 text-gray-200 hover:text-white mr-4" %>
      <%= link_to t('auth.sign_in'), new_user_session_path, class: "text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center" %>
    </div>
  <% end %>
</nav>

app/views/shared/_snackbar.html.erb
<div id="snackbar" class="transition-opacity opacity-100 fixed -translate-x-1/2 top-24 left-1/2 z-10 border py-3 px-4 rounded bg-green-100 text-green-700 border-green-700" >
  <%= snackbar_message %>
</div>